/*
 * Copyright 2026 ZeroClaw Community
 *
 * Licensed under the MIT License. See LICENSE in the project root.
 */

package com.zeroclaw.android.data.oauth

/**
 * PKCE (Proof Key for Code Exchange) state container for the OAuth 2.0
 * authorization code flow.
 *
 * Generated by [OpenAiOAuthManager.generatePkceState] and consumed by
 * both the authorization URL builder and the token exchange step.
 *
 * @property codeVerifier Cryptographically random base64url-encoded string
 *   (64 random bytes). Sent to the token endpoint to prove possession.
 * @property codeChallenge SHA-256 hash of [codeVerifier], base64url-encoded
 *   without padding. Included in the authorization URL.
 * @property state Random nonce for CSRF protection. Verified when the
 *   authorization server redirects back to the callback URI.
 */
data class PkceState(
    val codeVerifier: String,
    val codeChallenge: String,
    val state: String,
)
